### ISSUE TITLE
Package not found in POMDPs registry

### ISSUE THREAD

**Issue by dominikstrb** [JuliaPOMDP/BeliefGridValueIteration.jl#1]
When trying to install the package after adding the POMDPs registry, the package does not seem to be available in the registry:

```
ERROR: The following package names could not be resolved:
 * BeliefGridValueIteration (not found in project, manifest or registry)
Please specify by known `name=uuid`.
```

**Comment by MaximeBouton** [comment]
Thanks for letting us know, it should be fixed now. 
I will feature the package on the POMDPs.jl README sometimes soon.

**Comment by dominikstrb** [comment]
Thanks!
